# Protein Structure Exercise

In this notebook we will use `matplotlib` to investigate some real experimental data.

Protein structures can be determined by X-ray crystallography experiments and are conventionally recorded as [PDB files](https://en.wikipedia.org/wiki/Protein_Data_Bank_(file_format)), which are structured text files details about the experiment itself, together with the 3D coordinates of each atom within the structure.

We will work with some data derived from the [1HMP](https://www.rcsb.org/structure/1HMP) structure, namely the dihedral angles, $\phi$(phi) and $\psi$(psi), of the carbon backbone.

<center><img src="../Resources/dihedral.png" style="height:300px" alt="By Dcrjsr, vectorised Adam Rędzikowski - Own work, CC BY 3.0, https://commons.wikimedia.org/w/index.php?curid=24585750"/></center>


<div align=right>(Image by Dcrjsr, vectorised Adam Rędzikowski, CC BY 3.0)</div>


The data have been provided as a plain text file containing two columns of numbers ($\phi$ and $\psi$), separated by tabs. There is one row for every C$\alpha$ (i.e. backbone carbon atom) in the structure.

We can easily load the data into a 2-dimensional numpy array as shown:

In [17]:
import numpy as np
data = np.loadtxt('1hmp_mmtk.txt')

# showing just the first ten rows
data[:10,:]

array([[ -92.926842,   12.941312],
       [  65.796807, -162.229709],
       [ -81.132082,  121.413022],
       [ -85.523806,  137.173724],
       [-124.988754,   85.242472],
       [ -43.117225,  147.113709],
       [ -48.307914,  -29.941388],
       [ -88.163884,   -2.348568],
       [ -52.848368,  130.047635],
       [ -93.401285,   -4.973523]])

### Question: 
How many C$\alpha$ atoms are there in this structure?

---

### Task: Summarise the data
Calculate summary statistics for the variables $\phi$ and $\psi$.

---

### Task: Visualise the data

Find a suitable way to visualise the distributions of $\phi$ and $\psi$.

Are any of your summary statistics actually useful for this data set?

---

### Task: Joint distribution
Use a scatter plot to investigate the relationship between $\phi$ and $\psi$

### Task: Gaussian mixture model

You should see that there are are several distinct "patches" of data in the scatter plot. This implies that there are certain combinations of ($\phi$,$\psi$) that are preferred by the protein.

One potentially useful way to summarise this joint distribution is as a mixture of 2D Gaussian (aka "Normal") component distributions. Each component will have its own centre on the 2D $\phi$-$\psi$ plane.

We can fit a simple three-component [Gaussian mixture model](https://scikit-learn.org/stable/modules/generated/sklearn.mixture.GaussianMixture.html) like this:

In [184]:
from sklearn.mixture import GaussianMixture
gmm = GaussianMixture(n_components=3, covariance_type='diag', random_state=0).fit(data)

The resulting model can report the coordinates of the three component centres:

In [185]:
gmm.means_

array([[ -75.62480815,  -34.41713905],
       [-107.38123843,  136.61407598],
       [  79.6362865 ,    9.07039214]])

And their *variances* in $\phi$ and $\psi$:

In [186]:
gmm.covariances_

array([[ 661.76442444, 1146.28597329],
       [ 856.57467262,  479.22204016],
       [ 729.39694663, 8710.25293037]])

Can you now redraw the scatter plot, marking the centre of each fitted component and its standard deviation in $\phi$ and $\psi$?

### Question:
How could we improve on this model?

---

The general $\phi$-$\psi$ scatterplot is known as a [Ramachandran plot](https://en.wikipedia.org/wiki/Ramachandran_plot), describing the energetically favourable dihedral angles that are found in protein structures. - it is very useful for validation of structures that are computed from X-ray crystallography data.

Dihedral angle dataset was taken from
https://warwick.ac.uk/fac/sci/moac/people/students/peter_cock/r/ramachandran/
